apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  ports:
  - port: 9000
  selector:
    tier: middleware
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: middleware
  template:
    metadata:
      labels:
        app: php
        tier: middleware
    spec:
      imagePullSecrets:
      - name: local-registry
      containers:
      - name: php7-fpm
        image: 10.128.0.2:5000/middleware:3
        ports:
        - containerPort: 9000
          name: phpfpm
# Tips
# php maintenance/install.php --wiki "mStakX" --dbuser mediawiki --dbpass mediawiki --dbname mstakx_wiki --dbprefix mstakx --dbserver mysql --dbtype mysql --installdbpass password --installdbuser root --pass P@ssw0rd1234 mStakX admin
# $wgShowExceptionDetails = true;
# $wgShowDBErrorBacktrace = true;
# $wgShowSQLErrors = true;